; Retro Engine Config File.
[Game]
dataFile=Data.rsdk
devMenu=n
faceButtonFlip=n
enableControllerDebugging=n
username=Player 1
region=-1
gameType=1
language=0
dlcEnabled=n

[Video]
windowed=y
border=y
exclusiveFS=y
vsync=y
tripleBuffering=n
winWidth=848
winHeight=480
refreshRate=60
shaderSupport=y
screenShader=0
maxPixWidth=424

[Audio]
streamsEnabled=y
streamVolume=1.000000
sfxVolume=1.000000

[Keyboard Map 1]
up=0x26
down=0x28
left=0x25
right=0x27
buttonA=0x41
buttonB=0x53
buttonC=0x44
buttonX=0x51
buttonY=0x57
buttonZ=0x45
start=0xd
select=0x9

[Keyboard Map 2]
up=0x68
down=0x65
left=0x64
right=0x66
buttonA=0x4a
buttonB=0x4b
buttonC=0x0
buttonX=0x55
buttonY=0x49
buttonZ=0x0
start=0xdb
select=0xdd

[Keyboard Map 3]
up=0x0
down=0x0
left=0x0
right=0x0
buttonA=0x0
buttonB=0x0
buttonC=0x0
buttonX=0x0
